### ISSUE TITLE
Learn about Angular

### ISSUE THREAD

**Issue by JGieseWeb** [JGieseWeb/Stop-Bored#1]
#### Description

Learn what is needed to write a simple App

#### Tasks

Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.

- [ ] Read about Angular on the Official Webside.
- [ ] Follow the Path to Install 
- [ ] Adapt to own App
