### ISSUE TITLE
Implement the Random Button

### ISSUE THREAD

**Issue by JGieseWeb** [JGieseWeb/Stop-Bored#5]
#### Description

Create the Random button that show a random Activity

#### Screenshots

![image](https://user-images.githubusercontent.com/82370428/140904931-6393cf0d-4b56-44d5-bb1c-e69c9d09dcee.png)

#### Tasks

- [ ] Create or find the Image 
- [ ] Write the base Funciton
- [ ] Connect to Output Field
